# 1. Numpy Data Types and Type Casting

## Numpy Data Types : 

In [3]:
import numpy as np

In [4]:
# Array creation 
arr0 = np.array([1,2,3])
arr0

array([1, 2, 3])

### 

In [5]:
arr1 = np.array([1,2,3,4])
arr1

array([1, 2, 3, 4])

In [7]:
arr1.dtype

dtype('int32')

In [8]:
arr1 = np.array([1,2,3.6,4])
arr1

array([1. , 2. , 3.6, 4. ])

In [9]:
arr1.dtype

dtype('float64')

### 

In [10]:
ls = ["string",1,2,3.4,False]
arr2 = np.array(ls)
arr2    # all elements are converted in to the string format

array(['string', '1', '2', '3.4', 'False'], dtype='<U32')

### 

#### Data Types and example

### 

In [12]:
# If we want to change the datatype of the element while array creation 
# Example we need to create float numbers array
arr3 = np.array([1,2,3,4,5] , dtype = float)
arr3

array([1., 2., 3., 4., 5.])

In [13]:
arr3.dtype

dtype('float64')

In [14]:
arr3 = np.array([1,2,3,4,5] , dtype = np.float32)
arr3

array([1., 2., 3., 4., 5.], dtype=float32)

### 

In [15]:
arr4 = np.array([1.1,2.1,3,4], dtype = np.int64)
arr4
# By this error should come because there is float and how it can be convert to int

array([1, 2, 3, 4], dtype=int64)

### 

### 

## Type Casting : 

In [16]:
arr5 = np.array([1,2,3,4,5])
arr5

array([1, 2, 3, 4, 5])

In [17]:
arr5.dtype

dtype('int32')

In [18]:
new_arr5 = arr5.astype(np.float64) 
new_arr5

array([1., 2., 3., 4., 5.])

In [19]:
new_arr5.dtype

dtype('float64')

In [20]:
new_arr5_int_back = new_arr5.astype(np.int32)
new_arr5_int_back

array([1, 2, 3, 4, 5])

In [21]:
new_arr5_int_back.dtype

dtype('int32')

### 

### Type Casting Errors : 

In [22]:
arr6 = np.array([1,2,"String"])
New_arr6 = arr6.astype(np.int32)
New_arr6  # Here error is come that string value is can't be coverted to int

ValueError: invalid literal for int() with base 10: 'String'

### 

### 

# 2. Creation of Multi Dimensional Array

In [23]:
# Creation of 2d array by just providing two lists
arr7 = np.array([1,2,3],[4,5,6])
arr7

TypeError: Field elements must be 2- or 3-tuples, got '4'

In [24]:
# The error says that we provide two list in to the np.array() but it only takes only one list 
arr7 = np.array( [   [1,2,3],[4,5,6]   ] )  # We pass this two lists into one single list.
arr7

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
arr7.ndim

2

In [26]:
arr7.shape

(2, 3)

In [27]:
arr7.size  # Do multiplication of all the dimensions of the array to find the total no. of the elements present in array.

6

In [28]:
arr7.itemsize  # To find the Data size of the one element of array.

4

### 

### 

# 3. Array Reshaping --> Reshape, Ravel, Flatten

## Reshape  --> Used to reshape the array dimension without affecting elements.

In [29]:
arr8 = np.array([1,2,3,4,5,6])
arr8

array([1, 2, 3, 4, 5, 6])

In [30]:
arr8_reshaped = arr8.reshape(2,3)
arr8_reshaped

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
arr8_REreshaped = arr8_reshaped.reshape(3,2)
arr8_REreshaped

array([[1, 2],
       [3, 4],
       [5, 6]])

In [44]:
arr8_1D = arr8_REreshaped.reshape(-1)
arr8_1D

array([100,   2,   3,   4,   5,   6])

### 

## Ravel --> Used to convert nD array to 1D array.

In [32]:
arr9_ravel = arr8_REreshaped.ravel()
arr9_ravel

array([1, 2, 3, 4, 5, 6])

In [34]:
arr9_ravel[0] = 100 
arr9_ravel

array([100,   2,   3,   4,   5,   6])

In [39]:
arr8_REreshaped

array([[100,   2],
       [  3,   4],
       [  5,   6]])

### 

## Flatten --> Used to convert nD array to 1D array.

In [35]:
arr10_flatten = arr8_REreshaped.flatten()
arr10_flatten

array([100,   2,   3,   4,   5,   6])

In [36]:
arr10_flatten[0] = 1

In [37]:
arr10_flatten

array([1, 2, 3, 4, 5, 6])

In [40]:
arr8_REreshaped

array([[100,   2],
       [  3,   4],
       [  5,   6]])

### 

### Difference between ravel() and flatten()

### 

### 

# 4. Final Summay : 

#### Data Types and example