## 1. Numpy Introduction 

### What is Numpy ?

### Why we need Numpy because we already have Arrays and list in the python?

#### 1. Speed

In [3]:
# We want to do twice array element
# ex. a = [1,2,3,4,5,6,7,8,9] to a*2 = [2,4,6,8,10,12,14,16,18,20
import time
import numpy as np

In [13]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] * 10000
start = time.time()
for i in range(len(a)):
    a[i] = a[i]*2
print("\nTime taken for list:", time.time()- start)

# Time required to perform this operation using normal python array = 0.03 second


Time taken for list: 0.031194210052490234


In [14]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] * 10000
b = np.array(a)
start = time.time()
new_b = b*2
print("\nTime taken for numpy array:", time.time() - start)

# Time required to perform this operation using numpy = 0.0015 second


Time taken for numpy array: 0.0014951229095458984


#### 2. Memory Efficient 

In [17]:
import sys
a = [1, 2, 3, 4, 5]
arr = np.array(a) 
print("List size:", sys.getsizeof(a))
print("Array size:", arr.nbytes)

List size: 104
Array size: 20


#### 3. Direct Operation Functionality 

In [19]:
# Numpy provides us to perform operation directly without loop or other stuff.
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
new_a = a*2
new_a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [20]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
for i in range(len(a)):
    a[i] = a[i]*2
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

#### 4. Datatypes

In [21]:
A = [1,2.0,"Apple"]
A

[1, 2.0, 'Apple']

In [24]:
B = np.array([1,2.0,"Apple",True])
B   # Here all the values are converted in to the string data type means all element has same data type.

array(['1', '2.0', 'Apple', 'True'], dtype='<U32')

In [25]:
B[0] + 5  # Here we try to do string + integer which cause the error.

TypeError: can only concatenate str (not "int") to str

#### 5. Built In function 

In [28]:
Arr = np.array([1,1,1,2,3,4,4,4,4,5,6,7])
np.unique(Arr)  # This is function is not inside the python list built in function

array([1, 2, 3, 4, 5, 6, 7])

### 

### 

## 2. Installation of numpy in local system 

In [29]:
!pip install numpy

### 

## 3. Import numpy

In [30]:
import numpy as np  # as np means alias means we will use np everywhere where we needed instead to write whole numpy word

In [31]:
N = np.array([1,2,3])
N

array([1, 2, 3])

### 

## 4. Dimensions and Shape of an array

In [33]:
# Dimension : 0
arr0d = np.array(12)
arr0d.ndim

0

In [34]:
# Dimension : 1
arr1d = np.array([1,2,3])
arr1d.ndim

1

In [37]:
# Dimension : 2
arr2d = np.array([  [1,2,3],
                    [4,5,6]  ])
arr2d.ndim

2

In [42]:
arr2d.shape

(2, 3)

### 

## 5. Numpy array inbuilt functions

In [40]:
arr0 = np.arange(0,10,1)  # To generate numbers between range : start : stop(excluded) : step(1-by default)
arr0

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
arr0 = np.arange(0,10,2) 
arr0

array([0, 2, 4, 6, 8])

### 

In [44]:
arr1 = np.linspace(0,1,5)  # To generate no between range with even space : start : stop(included) : how many no count 
arr1

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### 

In [45]:
arr2 = np.logspace(1,3,3) # To generate 10^ values :  start : stop(included) : how many no count
arr2

array([  10.,  100., 1000.])

### 

In [46]:
arr3 = np.zeros(3)   # --> provide dimnsions(n) to make full of zeros nD array.
arr3

array([0., 0., 0.])

In [47]:
arr3 = np.zeros([2,3])
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [48]:
arr3 = np.zeros([2,3,4])
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [54]:
arr3 = np.zeros([2,3,4,5])
arr3

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

### 

In [52]:
arr4 = np.ones([2,4])
arr4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [53]:
arr4 = np.ones([2,4], dtype="int")
arr4

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

### 

In [56]:
arr5 = np.full(5, 7)
arr5

array([7, 7, 7, 7, 7])

In [55]:
arr5 = np.full([2,4], 7)
arr5

array([[7, 7, 7, 7],
       [7, 7, 7, 7]])

### 

In [58]:
arr6 = np.empty([2,4]) # To create uninitiated array without setting any values
arr6

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### 

### 

## 6. Numpy array generation with values

In [59]:
arr7 = np.random.rand(10)   # Random floats generator.
arr7

array([0.23387424, 0.55871171, 0.49820482, 0.05272438, 0.58645046,
       0.96919477, 0.66065558, 0.63537057, 0.90201602, 0.65844392])

In [60]:
arr7 = np.random.rand(2,3,4)
arr7

array([[[0.3518449 , 0.65285694, 0.19956574, 0.60625519],
        [0.74810886, 0.3739689 , 0.44149083, 0.62032679],
        [0.27835626, 0.6976309 , 0.92608581, 0.15923417]],

       [[0.91152631, 0.32396946, 0.87258344, 0.82161788],
        [0.53475291, 0.32737843, 0.1898471 , 0.7520584 ],
        [0.59873789, 0.44743759, 0.96013941, 0.14252415]]])

### 

In [62]:
arr8 = np.random.randn()  # random floats from standard normal distribution. (mean = 0 and standard deviation = 1)
arr8 

-1.015772927039055

In [63]:
arr8 = np.random.randn(4,5)  # random floats from standard normal distribution. (mean = 0 and standard deviation = 1)
arr8 

array([[-0.17287255, -0.6617008 ,  0.54875779, -2.08905631, -0.42854586],
       [ 1.10308296,  0.87226462, -1.32947021, -0.79916494, -0.59888129],
       [ 1.6505271 , -0.57333379, -0.65607514, -0.30969393,  0.67462918],
       [-0.24618771, -0.3274571 , -1.27633189, -0.02808126,  1.23334304]])

### 

In [64]:
arr9 = np.random.randint(4,5)  # random integer and (start,stop,size=())
arr9

4

In [67]:
arr9 = np.random.randint(4,10,size=(3,6))  # random integer and (start,stop,size=()) and stop is excluded.
arr9

array([[6, 4, 5, 5, 4, 9],
       [9, 4, 6, 8, 8, 4],
       [7, 7, 8, 4, 8, 7]])

### 

## 7. Summary Table of all the functions which we learnt in this notebook : 