# 1. Arithmetic Operation on Arrays

In [2]:
import numpy as np

In [3]:
# Array creation 
arr0 = np.array([1,2,3])
arr1 = np.array([4,5,6])

In [5]:
# Addition
print(arr0+arr1)

[5 7 9]


In [7]:
# Subtraction 
print(arr1-arr0)

[3 3 3]


In [8]:
# Multiplication
print(arr0*arr1)

[ 4 10 18]


In [9]:
# Division
print(arr1/arr0)   # By default float division but want int division then...

[4.  2.5 2. ]


In [10]:
# Integer Division
print(arr1//arr0)

[4 2 2]


In [11]:
# Modulo
print(arr1%arr0)

[0 1 0]


In [12]:
# Exponenet
print(arr0**2)

[1 4 9]


### 

### 

# 2. Universal Functions --> ufuncs

In [13]:
# Creation of 2d array by just providing two lists
arr2 = np.array([1,4,9,16])
arr2

array([ 1,  4,  9, 16])

### 1. Square Root --> np.sqrt()

In [14]:
np.sqrt(arr2)

array([1., 2., 3., 4.])

### 2. Exponential --> np.exp()  --> e^x --> x is an intger

In [15]:
np.exp(arr2)

array([2.71828183e+00, 5.45981500e+01, 8.10308393e+03, 8.88611052e+06])

In [16]:
np.exp([1,2])

array([2.71828183, 7.3890561 ])

### 3. Sine Function --> np.sin()

In [18]:
angles = np.array([0,np.pi/2,np.pi])
np.sin(angles)

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

### 


### 

# 3. Indexing and Slicing of an array

### Indexing

In [19]:
arr3 = np.array([1,2,3,4,5])
arr3

array([1, 2, 3, 4, 5])

In [20]:
arr3[4]

5

In [21]:
arr3[-1]

5

### Slicing

In [22]:
arr4 = np.array([1,2,3,4,5])
arr4

array([1, 2, 3, 4, 5])

In [23]:
arr4[0:3:1]

array([1, 2, 3])

In [24]:
arr4[-1:-4:-1]

array([5, 4, 3])

In [25]:
arr4[-1:-4]   
# If step = -1 is not given during use of the negative indexing we do not get output and provide [] (empty string) as ouput.

array([], dtype=int32)

In [27]:
# If want to access such that space = 2
arr4[::2]

array([1, 3, 5])

In [28]:
arr4[::]

array([1, 2, 3, 4, 5])

### 

### 

# 4. Multi Dimensional Slicing

In [30]:
matrix = np.array([  [1,2,3],
                     [4,5,6],
                     [7,8,9]   ])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
# To access first two rows of a matrix
matrix[0:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
# Want to row 1 and 2 and also same want in column
matrix[1: , 1: ]

array([[5, 6],
       [8, 9]])

### 

### 

# 5. Index Arrays --> Advanced Indexing

In [33]:
# np.take()  --> Built in function to perform indexing and slicing
arr5 = np.array([10,20,30,40,50])
ind = [1,3,4]
np.take(arr5,ind)

array([20, 40, 50])

### 

### 

# 6. Iterating with 

## A. nditer()

In [34]:
arr6 = np.array([[10,20],[30,40]])
arr6

array([[10, 20],
       [30, 40]])

In [35]:
for i in np.nditer(arr6):
    print(i**2, end=" ")

100 400 900 1600 

### 

## B. ndenumerate()  --> we need to pass index and value both as iterator.

In [36]:
arr6 = np.array([[10,20],[30,40]])
arr6

array([[10, 20],
       [30, 40]])

In [37]:
for ind, i in np.ndenumerate(arr6):
    print(ind,i)  # This means at index 0,0 (0th row and 0th column), the value is 10

(0, 0) 10
(0, 1) 20
(1, 0) 30
(1, 1) 40


### 

### 

# 7. Views vs Copies

### Views

In [39]:
arr7 = np.array([1,2,3,4,5])
arr7

array([1, 2, 3, 4, 5])

In [40]:
View = arr7[2:4]
View

array([3, 4])

In [41]:
View[0] = 300
View

array([300,   4])

In [42]:
arr7

array([  1,   2, 300,   4,   5])

### 

### Copies

In [43]:
arr8 = np.array([1,2,3,4,5])
arr8

array([1, 2, 3, 4, 5])

In [44]:
Copy = arr8[1:4].copy()
Copy

array([2, 3, 4])

In [45]:
Copy[0] = 200
Copy

array([200,   3,   4])

In [46]:
arr8

array([1, 2, 3, 4, 5])

### 

### 

# 8. Final Summay : 